services:
  - type: web
    name: fixybotservice
    runtime: docker
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: KB_URL
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_TOKEN
        sync: false
